### ISSUE TITLE
Dash Interface

### ISSUE THREAD

**Issue by chuangw6** [UBC-MDS/532-Group21#8]
Please post any major issue regarding Dash interface development under this issue thread.

**Comment by eboylestanley** [comment]
PR created with the following changes:  

- Added the line chart.  When education ratio is selected the display seems to be cutting off at 1970.  Not sure if this is due to our preprocessing or if we are missing values prior to 1970.  I also think it might be nice to make the y-axis values variable, so we aren't always starting from zero.   
- Added titles and axis labels on the bar and line charts.  I also had trouble figuring out how to access the stat label value to add to the title and axis labels.  Currently its showing the stat value which does not look good. 
- Modified the filters so they default to None.  The graphs now display if no filters are selected, some filters are selected or all filters are selected (except the Population density).  I did this through various if statements, it is not the cleanest code so could maybe be updated later. 
- Other minor changes

![image](https://user-images.githubusercontent.com/63200505/105204975-b76f5d80-5b12-11eb-8303-1a1dbd964ca7.png)

**Comment by eboylestanley** [comment]
See milestone 2 release from completed dash app.
